- name: Initialise Infrastructure
  import_playbook: 01-infrastructure.yml
- name: Initialise Keepalived
  import_playbook: 02-keepalived.yml
- name: Initialise kubernetes
  import_playbook: 03-init-k8s.yml
- name: Initialise argocd
  import_playbook: 04-argocd.yml
