---
name: Conventional Commits

# yamllint disable-line rule:truthy
on:
  pull_request:
    # yamllint disable-line rule:brackets
    branches: [ main ]

jobs:
  build:
    name: Conventional Commits
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # yamllint disable-line rule:line-length
          allowed-commit-types: "feat,fix,chore,BREAKING CHANGE,docs,test,refactor"
