---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint ansible yamllint
          ansible-galaxy collection install community.general

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Create ansible password file
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: echo $ANSIBLE_VAULT_PASSWORD > .vault_password

      - name: Lint YAML files
        run: |
          yamllint .

      - name: Lint Ansible code
        run: |
          ANSIBLE_VAULT_PASSWORD_FILE=.vault_password ansible-lint

      - name: Clean up ansible secret
        run: rm .vault_password
